---
- name: Deploy Inception Project
  hosts: wordpress_servers
  become: true 

  vars:
    data_path: "/home/{{ ansible_user }}/data"
    project_path: "/home/{{ ansible_user }}/inception"

  tasks:
    - name: Create data directories
      file:
        path: "{{ data_path }}/{{ item }}"
        state: directory
        mode: '0777'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
      with_items:
        - mysql
        - html

    - name: Deploy project files
      copy:
        src: "../../inception/"
        dest: "{{ project_path }}"
        mode: preserve
      become: false

    - name: Fix permissions for Docker sock
      file:
        path: /var/run/docker.sock
        mode: '0666'

    - name: Run make
      command: make
      args:
        chdir: "{{ project_path }}"
      become: false