---
- name: Deploy Inception Project
  hosts: wordpress_servers
  become: true 

  tasks:
    - name: Create volume directories
      file:
        path: "/home/{{ ansible_user }}/inception/volumes/{{ item }}"
        state: directory
        mode: '0755'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
      with_items:
        - wordpress
        - mysql

    - name: Deploy Inception files
      become: false
      block:
        - name: Create project directories
          file:
            path: "/home/{{ ansible_user }}/inception/services/{{ item }}"
            state: directory
            mode: '0755'
          with_items:
            - nginx
            - wordpress
            - mysql

    - name: Copy project files
      copy:
        src: "../../inception/"
        dest: "/home/{{ ansible_user }}/inception/"
        mode: preserve

